// Seeds the demo RFx: 30 canonical lanes + 5 vendors (A-E).
// Run with: npm run seed
//
// This is step 1 of the build sequence (§8 of the architecture plan) — the
// fabricated vendor documents (§4.2 of the functional plan) and downloadable
// buyer templates are generated by a separate script layered on top of this.

import { connectToDatabase } from "../lib/db/connect";
import { RfxModel } from "../lib/db/models/Rfx";
import { LaneModel } from "../lib/db/models/Lane";
import { VendorModel } from "../lib/db/models/Vendor";
import { CANONICAL_LANES } from "../lib/fixtures/canonicalLanes";
import { generateAndUploadBuyerTemplates } from "../lib/files/generateTemplates";

const DEMO_RFX_TITLE = "PTL Freight Lanes — FY26 Q3";

const VENDORS = [
  { code: "A", name: "Bharat Roadlines Pvt Ltd" },
  { code: "B", name: "Continental Cargo Movers" },
  { code: "C", name: "Sagar Transport Co." },
  { code: "D", name: "Speedway Logistics" },
  { code: "E", name: "TransGlobal Freight Solutions" },
];

async function main() {
  await connectToDatabase();

  // Idempotent: reuse the demo RFx if it already exists, otherwise create it.
  let rfx = await RfxModel.findOne({ title: DEMO_RFX_TITLE });
  if (!rfx) {
    rfx = await RfxModel.create({ title: DEMO_RFX_TITLE, status: "active" });
    console.log(`Created RFx ${rfx._id}`);
  } else {
    console.log(`Reusing existing RFx ${rfx._id}`);
  }

  // Vendors are global entities — upsert by code.
  const vendorDocs = [];
  for (const v of VENDORS) {
    const vendor = await VendorModel.findOneAndUpdate(
      { code: v.code },
      { $setOnInsert: { name: v.name, code: v.code } },
      { upsert: true, returnDocument: "after" }
    );
    vendorDocs.push(vendor);
  }
  console.log(`Ensured ${vendorDocs.length} vendors:`, vendorDocs.map((v) => `${v.code}=${v.name}`).join(", "));

  // Lanes: replace this RFx's lane list wholesale so re-running seed stays
  // consistent with lib/fixtures/canonicalLanes.ts.
  await LaneModel.deleteMany({ rfxId: rfx._id });
  const laneDocs = await LaneModel.insertMany(
    CANONICAL_LANES.map((lane) => ({ ...lane, rfxId: rfx._id }))
  );
  console.log(`Inserted ${laneDocs.length} lanes for RFx ${rfx._id}`);

  // Buyer-side downloadable templates (§4.1 of the functional plan).
  const templates = await generateAndUploadBuyerTemplates(rfx._id.toString(), CANONICAL_LANES);
  rfx.laneListBlobUrl = templates.laneListUrl;
  rfx.questionnaireTemplateBlobUrl = templates.questionnaireUrl;
  rfx.termsTemplateBlobUrl = templates.termsUrl;
  await rfx.save();
  console.log("Generated and uploaded buyer templates:", templates);

  console.log("\nSeed complete.");
  console.log(`RFx ID: ${rfx._id}`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
